version: '3'
services:
  postgres:
    container_name: lablibrary-db
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/db/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
